package content.ecosystem.http4k.reference.model_context_protocol

import org.http4k.mcp.SamplingResponse
import org.http4k.mcp.model.Content
import org.http4k.mcp.model.ModelIdentifier
import org.http4k.mcp.model.ModelSelector
import org.http4k.mcp.model.Role.assistant
import org.http4k.mcp.model.StopReason
import org.http4k.mcp.server.capability.IncomingSamplingCapability
import org.http4k.routing.bind

fun SampleFromOurLocalLlm(): IncomingSamplingCapability {
    val llmName = ModelIdentifier.of("my-llm")

    return ModelSelector(llmName) bind {
        listOf(
            SamplingResponse(
                llmName,
                assistant,
                Content.Text("The first message generated by the server")
            ),
            SamplingResponse(
                llmName,
                assistant,
                Content.Text("The last message generated by the server"),
                StopReason.of("end") // this is the last message
            )
        ).asSequence()
    }
}

